# Oļegs Korsaks, 051RDB146

In [1]:
from math import exp
from operator import methodcaller

import numpy as np
import tensorflow as tf

from sklearn.datasets import load_iris

In [2]:
letters = [
    ['A',[0,1,0,1,0,1,1,1,1,1,0,1,1,0,1],[1,0,0]],
    ['E',[1,1,1,1,0,0,1,1,0,1,0,0,1,1,1],[1,0,0]],
    ['D',[1,1,0,1,0,1,1,0,1,1,0,1,1,1,0],[1,0,0]],
    ['B',[1,1,0,1,0,1,1,1,0,1,0,1,1,1,0],[0,1,0]],
    ['C',[1,1,1,1,0,0,1,0,0,1,0,0,1,1,1],[0,1,0]],
    ['F',[1,1,1,1,0,0,1,1,0,1,0,0,1,0,0],[0,1,0]],
    ['G',[1,1,1,1,0,0,1,0,1,1,0,1,1,1,1],[0,0,1]],
    ['H',[1,0,1,1,0,1,1,1,1,1,0,1,1,0,1],[0,0,1]],
    ['I',[0,1,0,0,1,0,0,1,0,0,1,0,0,1,0],[0,0,1]],
]

In [3]:
def a_step(val):
    return int(val>0)


def a_lin(val):
    if val <= 0:
        return 0
    elif val > 5:
        return 1
    
    return val/5


def a_sigmoid(val):
    return 1.0 / (1.0+exp(-val))


def a_tanh(val):
    return (exp(val)-exp(-val)) / (exp(val)+exp(-val))

In [4]:
learning_rate = 0.1


class Neiron:
    def __init__(self, in_size):
        self.weights = np.zeros(in_size)
        self.w0 = 0

    def classify(self, incoming_signals):
        net = np.dot(incoming_signals, self.weights) + self.w0
        
        return a_step(net)
    
    def learn(self, incoming_signals, c):
        y = self.classify(incoming_signals)
        delta = c - y
        
        if delta:
            for i in range(len(self.weights)):
                self.weights[i] += delta * learning_rate * incoming_signals[i]

            self.w0 += delta * learning_rate

In [5]:
def run_neirons(data: list, neiron_class, in_size: int, class_count: int, epoch_count: int = 100):
    neirons = tuple(neiron_class(in_size) for _ in range(class_count))
    
    for epoch in range(epoch_count):
        for sample in data:
            for i, neiron in enumerate(neirons):
                neiron.learn(sample[1], sample[2][i])
    
    for sample in data:
        method = methodcaller('classify', sample[1])
        print(f'{sample[0]} {tuple(map(method, neirons))}')
    
    for neiron in neirons:
        print(neiron.weights)

In [6]:
run_neirons(letters, Neiron, 15, 3, 100)

A (1, 0, 0)
E (1, 0, 0)
D (1, 0, 0)
B (0, 1, 0)
C (0, 1, 0)
F (0, 1, 0)
G (0, 0, 1)
H (0, 0, 1)
I (0, 0, 1)
[-0.7  0.5 -0.8  0.  -0.6 -0.3  0.   0.9  1.8  0.  -0.6 -1.   0.   0.3
  0.4]
[ 0.2  0.2 -0.4  0.2 -0.2  0.4  0.2 -0.7 -1.7  0.2 -0.2 -0.1  0.2  0.2
 -0.4]
[ 0.2 -0.3  0.3 -0.2  0.3 -0.1 -0.2 -0.2  0.4 -0.2  0.3  0.4 -0.2  0.1
 -0.1]


In [7]:
iris = load_iris()
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(4, kernel_regularizer=tf.keras.regularizers.l2(0.1), activation='sigmoid', input_shape=(4, )))
model.add(tf.keras.layers.Dense(3, activation='softmax'))
model.compile(optimizer='adam', loss='binary_crossentropy')

targets = np.zeros((len(iris.target), 3))

for ti, iris_target in enumerate(iris.target):
    targets[ti][iris_target] = 1

model.fit(iris.data, targets, epochs=1000, verbose=0)
predictions = model.predict(iris.data)

print(predictions)

[[0.96668833 0.02935013 0.00396155]
 [0.96336347 0.03215238 0.00448412]
 [0.9714252  0.02534266 0.00323216]
 [0.96314204 0.03233153 0.00452637]
 [0.9686563  0.02768597 0.00365768]
 [0.94679517 0.04582908 0.00737569]
 [0.96867645 0.0276666  0.00365701]
 [0.9621201  0.03318491 0.00469494]
 [0.9674865  0.02868117 0.00383235]
 [0.96191317 0.03336633 0.00472048]
 [0.9610681  0.03406187 0.00487006]
 [0.959469   0.0353935  0.00513751]
 [0.9664424  0.02956622 0.00399138]
 [0.9800699  0.01792623 0.00200389]
 [0.97265846 0.02429011 0.00305147]
 [0.9615265  0.03366091 0.00481253]
 [0.96818125 0.0280821  0.00373657]
 [0.96471304 0.03100933 0.00427765]
 [0.9432247  0.04875365 0.00802157]
 [0.9634827  0.03203423 0.00448311]
 [0.9445889  0.0476564  0.00775463]
 [0.9600743  0.03488079 0.00504489]
 [0.9829754  0.01539446 0.00163013]
 [0.9377526  0.05318629 0.00906102]
 [0.94022316 0.05118942 0.00858739]
 [0.95114523 0.04229524 0.00655958]
 [0.9515818  0.04191586 0.00650233]
 [0.9609931  0.0341266  0.00

## Mājasdarbs 1

Pārveidosim neirona klasi, lai viņš varētu klasificēt 4 klašu simbolus. Pievienosim ! _ un . simbolus

In [8]:
letters = [
    ['A',[0,1,0,1,0,1,1,1,1,1,0,1,1,0,1],[1,0,0,0]],
    ['E',[1,1,1,1,0,0,1,1,0,1,0,0,1,1,1],[1,0,0,0]],
    ['D',[1,1,0,1,0,1,1,0,1,1,0,1,1,1,0],[1,0,0,0]],
    ['B',[1,1,0,1,0,1,1,1,0,1,0,1,1,1,0],[0,1,0,0]],
    ['C',[1,1,1,1,0,0,1,0,0,1,0,0,1,1,1],[0,1,0,0]],
    ['F',[1,1,1,1,0,0,1,1,0,1,0,0,1,0,0],[0,1,0,0]],
    ['G',[1,1,1,1,0,0,1,0,1,1,0,1,1,1,1],[0,0,1,0]],
    ['H',[1,0,1,1,0,1,1,1,1,1,0,1,1,0,1],[0,0,1,0]],
    ['I',[0,1,0,0,1,0,0,1,0,0,1,0,0,1,0],[0,0,1,0]],
    
    ['!',[0,1,0,0,1,0,0,1,0,0,0,0,0,1,0],[0,0,0,1]],
    ['_',[0,0,0,0,0,0,0,0,0,0,0,0,1,1,1],[0,0,0,1]],
    ['.',[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],[0,0,0,1]],
]


class NeironHome:
    def __init__(self, in_size):
        self.weights = np.zeros(in_size)
        self.w0 = 0

    def classify(self, incoming_signals):
        net = np.dot(incoming_signals, self.weights) + self.w0
        
        return a_sigmoid(net)
    
    def learn(self, incoming_signals, c):
        y = self.classify(incoming_signals)
        delta = c - y
        
        if delta:
            for i in range(len(self.weights)):
                self.weights[i] += delta * learning_rate * incoming_signals[i]

            self.w0 += delta * learning_rate

In [9]:
run_neirons(letters, NeironHome, 15, 4, 1000)

A (0.9975535051097201, 6.660629571448497e-06, 0.008248493415553408, 0.00013232113048282796)
E (0.8293688905071558, 0.07107663617372244, 0.00345475745807826, 0.0008908342725369956)
D (0.8834289329308431, 0.040197189905192325, 0.005393751338105291, 0.000374360388021805)
B (0.06296538404255056, 0.9611077227614221, 2.5487150667717718e-05, 0.00044414160389372084)
C (0.08063124850588929, 0.941473518306242, 0.00588321544731504, 0.0016078235509806357)
F (0.02633476838322883, 0.9911138221082045, 0.0034084107149066696, 2.9723027415453927e-05)
G (0.04066958299013252, 0.00015968439826207983, 0.9849054420714136, 0.0002711874602893066)
H (0.02117992296299061, 1.3000067100018376e-05, 0.9923537292619337, 1.8435006117880236e-05)
I (0.0037253089873815924, 2.5566882336613036e-05, 0.9800763983367607, 0.02047026562186848)
! (0.018415486080804077, 4.3871158090628676e-05, 0.013755496597630701, 0.9781077632338467)
_ (0.00838609151522248, 0.00038552142987693667, 0.0020254630608827185, 0.9968259609187382)
. (0.

**Ir redzams, ka "!", "\_" un "." simboli tiek klasificēti kā 4. klase. Citu burtu klasifikācija nemainās.**

Pārtaisīsim TensorFlow kodu, lai viņš klasificētu burtus:

In [10]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(15, kernel_regularizer=tf.keras.regularizers.l2(0.1), activation='sigmoid', input_shape=(15, )))
model.add(tf.keras.layers.Dense(4, activation='softmax'))
model.compile(optimizer='adam', loss='binary_crossentropy')

np_letters = np.array(tuple(np.array(letter[1]) for letter in letters))
print(np_letters)
targets = np.array(tuple(np.array(letter[2]) for letter in letters))
print(targets)

model.fit(np_letters, targets, epochs=1000, verbose=0)
predictions = model.predict(np_letters)

print(predictions)

[[0 1 0 1 0 1 1 1 1 1 0 1 1 0 1]
 [1 1 1 1 0 0 1 1 0 1 0 0 1 1 1]
 [1 1 0 1 0 1 1 0 1 1 0 1 1 1 0]
 [1 1 0 1 0 1 1 1 0 1 0 1 1 1 0]
 [1 1 1 1 0 0 1 0 0 1 0 0 1 1 1]
 [1 1 1 1 0 0 1 1 0 1 0 0 1 0 0]
 [1 1 1 1 0 0 1 0 1 1 0 1 1 1 1]
 [1 0 1 1 0 1 1 1 1 1 0 1 1 0 1]
 [0 1 0 0 1 0 0 1 0 0 1 0 0 1 0]
 [0 1 0 0 1 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]
[[0.28988642 0.27545223 0.25788447 0.17677693]
 [0.2788191  0.27595928 0.25626993 0.18895164]
 [0.287445   0.27697244 0.25717753 0.17840494]
 [0.28627643 0.2789586  0.2563933  0.17837162]
 [0.27245513 0.2714314  0.25541538 0.20069805]
 [0.2802476  0.2782415  0.2563817  0.18512918]
 [0.2886852  0.27871957 0.2583197  0.17427544]
 [0.2964416  0.28238034 0.25931722 0.16186085]
 [0.18800709 0.20144749 0.2288997  0.3816457 ]
 [0.18627086 0.19988199 0.22707424 0.38677293]


**Interesanti**, bet TensorFlow versija apstiprināja manas šaubas par "I" un "!" lidzīguma problēmu, kāmēr bez TensorFlow klasifikācija nostrādāja pareizi. Ar parējiem burtiem arī ir redzamas problēmas - B tiek pieskaitīts pie 2. klases. Pārbaudīšu, vai epohu skaits uzlabos situāciju:

In [15]:
model.fit(np_letters, targets, epochs=10000, verbose=0)
predictions = model.predict(np_letters)

print(predictions)

[[9.99496937e-01 1.34420761e-05 4.69973922e-04 1.96926376e-05]
 [9.58357334e-01 3.75816748e-02 3.98055511e-03 8.04931624e-05]
 [9.84754920e-01 1.26729151e-02 2.49978015e-03 7.24810598e-05]
 [1.14166336e-02 9.88363326e-01 1.60726486e-05 2.03947158e-04]
 [1.35539323e-02 9.86042798e-01 2.82395951e-04 1.20917604e-04]
 [5.82982844e-04 9.99350369e-01 2.59106801e-05 4.07900552e-05]
 [3.38550122e-03 2.59130538e-05 9.96582687e-01 5.95227675e-06]
 [5.73314552e-04 3.84255964e-06 9.99408841e-01 1.40319144e-05]
 [3.71587783e-04 1.54227200e-06 9.98306394e-01 1.32054905e-03]
 [3.75623669e-04 1.44760370e-05 8.78414372e-04 9.98731434e-01]
 [1.30036888e-05 2.23610932e-05 2.46267791e-05 9.99939919e-01]
 [1.17278951e-07 1.06457310e-05 6.33963236e-06 9.99982953e-01]]
