<center><img src="./images/rtu_logo_lv.png" alt="RTU" title="RTU" width="150em"/></center>

<center><b>RĪGAS TEHNISKĀ UNIVERSITĀTE</b></center>
<center><b>DATORZINĀTNES UN INFORMĀCIJAS TEHNOLOĢIJAS FAKULTĀTE</b></center>
<center><b>Priekšmeta "Ievads mākslīgos neironu tīklos"</b></center><center>

<center><b>1. mājasdarbs</b></center>

<div style="text-align: right">
    LDsI 12300 Lietišķo datorsistēmu institūts<br>
    RDBD0 Datorsistēmas<br>
    <b>3. kursa 3. grupas</b> pilna laika klātienes <b>students</b><br>
    Oļegs Korsaks<br>
    <b>Studenta apliecības Nr.: </b>051RDB146<br>
</div>
<center><b>Rīga, 2021</b></center>
<div style="display:none">\pagebreak</div>

***

In [1]:
from math import exp
from operator import methodcaller

import numpy as np
import tensorflow as tf

In [2]:
letters = [
    ['A',[0,1,0,1,0,1,1,1,1,1,0,1,1,0,1],[1,0,0]],
    ['E',[1,1,1,1,0,0,1,1,0,1,0,0,1,1,1],[1,0,0]],
    ['D',[1,1,0,1,0,1,1,0,1,1,0,1,1,1,0],[1,0,0]],
    ['B',[1,1,0,1,0,1,1,1,0,1,0,1,1,1,0],[0,1,0]],
    ['C',[1,1,1,1,0,0,1,0,0,1,0,0,1,1,1],[0,1,0]],
    ['F',[1,1,1,1,0,0,1,1,0,1,0,0,1,0,0],[0,1,0]],
    ['G',[1,1,1,1,0,0,1,0,1,1,0,1,1,1,1],[0,0,1]],
    ['H',[1,0,1,1,0,1,1,1,1,1,0,1,1,0,1],[0,0,1]],
    ['I',[0,1,0,0,1,0,0,1,0,0,1,0,0,1,0],[0,0,1]],
]

In [3]:
def a_step(val):
    return int(val>0)


def a_lin(val):
    if val <= 0:
        return 0
    elif val > 5:
        return 1
    
    return val/5


def a_sigmoid(val):
    return 1.0 / (1.0+exp(-val))


def a_tanh(val):
    return (exp(val)-exp(-val)) / (exp(val)+exp(-val))

In [4]:
learning_rate = 0.1


class Neiron:
    def __init__(self, in_size):
        self.weights = np.zeros(in_size)
        self.w0 = 0

    def classify(self, incoming_signals):
        net = np.dot(incoming_signals, self.weights) + self.w0
        
        return a_step(net)
    
    def learn(self, incoming_signals, c):
        y = self.classify(incoming_signals)
        delta = c - y
        
        if delta:
            for i in range(len(self.weights)):
                self.weights[i] += delta * learning_rate * incoming_signals[i]

            self.w0 += delta * learning_rate

In [5]:
def run_neirons(data: list, neiron_class, in_size: int, class_count: int, epoch_count: int = 100):
    neirons = tuple(neiron_class(in_size) for _ in range(class_count))
    
    for epoch in range(epoch_count):
        for sample in data:
            for i, neiron in enumerate(neirons):
                neiron.learn(sample[1], sample[2][i])
    
    for sample in data:
        method = methodcaller('classify', sample[1])
        print(f'{sample[0]} {tuple(map(method, neirons))}')
    
    for neiron in neirons:
        print(neiron.weights)

In [6]:
run_neirons(letters, Neiron, 15, 3, 100)

A (1, 0, 0)
E (1, 0, 0)
D (1, 0, 0)
B (0, 1, 0)
C (0, 1, 0)
F (0, 1, 0)
G (0, 0, 1)
H (0, 0, 1)
I (0, 0, 1)
[-0.7  0.5 -0.8  0.  -0.6 -0.3  0.   0.9  1.8  0.  -0.6 -1.   0.   0.3
  0.4]
[ 0.2  0.2 -0.4  0.2 -0.2  0.4  0.2 -0.7 -1.7  0.2 -0.2 -0.1  0.2  0.2
 -0.4]
[ 0.2 -0.3  0.3 -0.2  0.3 -0.1 -0.2 -0.2  0.4 -0.2  0.3  0.4 -0.2  0.1
 -0.1]


## Mājasdarbs 1

Pārveidosim neirona klasi, lai viņš varētu klasificēt 4 klašu simbolus. Pievienosim ! _ un . simbolus

In [7]:
letters = [
    ['A',[0,1,0,1,0,1,1,1,1,1,0,1,1,0,1],[1,0,0,0]],
    ['E',[1,1,1,1,0,0,1,1,0,1,0,0,1,1,1],[1,0,0,0]],
    ['D',[1,1,0,1,0,1,1,0,1,1,0,1,1,1,0],[1,0,0,0]],
    ['B',[1,1,0,1,0,1,1,1,0,1,0,1,1,1,0],[0,1,0,0]],
    ['C',[1,1,1,1,0,0,1,0,0,1,0,0,1,1,1],[0,1,0,0]],
    ['F',[1,1,1,1,0,0,1,1,0,1,0,0,1,0,0],[0,1,0,0]],
    ['G',[1,1,1,1,0,0,1,0,1,1,0,1,1,1,1],[0,0,1,0]],
    ['H',[1,0,1,1,0,1,1,1,1,1,0,1,1,0,1],[0,0,1,0]],
    ['I',[0,1,0,0,1,0,0,1,0,0,1,0,0,1,0],[0,0,1,0]],
    
    ['!',[0,1,0,0,1,0,0,1,0,0,0,0,0,1,0],[0,0,0,1]],
    ['_',[0,0,0,0,0,0,0,0,0,0,0,0,1,1,1],[0,0,0,1]],
    ['.',[0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],[0,0,0,1]],
]


class NeironHome:
    def __init__(self, in_size):
        self.weights = np.zeros(in_size)
        self.w0 = 0

    def classify(self, incoming_signals):
        net = np.dot(incoming_signals, self.weights) + self.w0
        
        return a_sigmoid(net)
    
    def learn(self, incoming_signals, c):
        y = self.classify(incoming_signals)
        delta = c - y
        
        if delta:
            for i in range(len(self.weights)):
                self.weights[i] += delta * learning_rate * incoming_signals[i]

            self.w0 += delta * learning_rate

In [8]:
run_neirons(letters, NeironHome, 15, 4, 1000)

A (0.9975535051097201, 6.660629571448497e-06, 0.008248493415553408, 0.00013232113048282796)
E (0.8293688905071558, 0.07107663617372244, 0.00345475745807826, 0.0008908342725369956)
D (0.8834289329308431, 0.040197189905192325, 0.005393751338105291, 0.000374360388021805)
B (0.06296538404255056, 0.9611077227614221, 2.5487150667717718e-05, 0.00044414160389372084)
C (0.08063124850588929, 0.941473518306242, 0.00588321544731504, 0.0016078235509806357)
F (0.02633476838322883, 0.9911138221082045, 0.0034084107149066696, 2.9723027415453927e-05)
G (0.04066958299013252, 0.00015968439826207983, 0.9849054420714136, 0.0002711874602893066)
H (0.02117992296299061, 1.3000067100018376e-05, 0.9923537292619337, 1.8435006117880236e-05)
I (0.0037253089873815924, 2.5566882336613036e-05, 0.9800763983367607, 0.02047026562186848)
! (0.018415486080804077, 4.3871158090628676e-05, 0.013755496597630701, 0.9781077632338467)
_ (0.00838609151522248, 0.00038552142987693667, 0.0020254630608827185, 0.9968259609187382)
. (0.

**Ir redzams, ka "!", "\_" un "." simboli tiek klasificēti kā 4. klase. Citu burtu klasifikācija nemainās.**

Pārtaisīsim TensorFlow kodu, lai viņš klasificētu burtus:

In [9]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(15, kernel_regularizer=tf.keras.regularizers.l2(0.1), activation='sigmoid', input_shape=(15, )))
model.add(tf.keras.layers.Dense(4, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy')

np_letters = np.array(tuple(np.array(letter[1]) for letter in letters))
print(np_letters)
targets = np.array(tuple(np.array(letter[2]) for letter in letters))
print(targets)

model.fit(np_letters, targets, epochs=1000, verbose=0)
predictions = model.predict(np_letters)

print(predictions)

[[0 1 0 1 0 1 1 1 1 1 0 1 1 0 1]
 [1 1 1 1 0 0 1 1 0 1 0 0 1 1 1]
 [1 1 0 1 0 1 1 0 1 1 0 1 1 1 0]
 [1 1 0 1 0 1 1 1 0 1 0 1 1 1 0]
 [1 1 1 1 0 0 1 0 0 1 0 0 1 1 1]
 [1 1 1 1 0 0 1 1 0 1 0 0 1 0 0]
 [1 1 1 1 0 0 1 0 1 1 0 1 1 1 1]
 [1 0 1 1 0 1 1 1 1 1 0 1 1 0 1]
 [0 1 0 0 1 0 0 1 0 0 1 0 0 1 0]
 [0 1 0 0 1 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]
[[0.4057499  0.2425949  0.2663701  0.08528512]
 [0.30167082 0.33106974 0.24818288 0.11907658]
 [0.37733    0.2791558  0.24807459 0.09543963]
 [0.36596152 0.3197736  0.21923439 0.09503048]
 [0.2787835  0.32859215 0.24841893 0.14420544]
 [0.2959681  0.35381326 0.2363469  0.11387179]
 [0.32631972 0.27099514 0.30222756 0.10045753]
 [0.33388078 0.25433013 0.3253257  0.08646336]
 [0.0913469  0.1572321  0.279085   0.47233593]
 [0.08640224 0.15662202 0.23808245 0.51889324]


**Interesanti**, bet TensorFlow versija apstiprināja manas šaubas par "I" un "!" lidzīguma problēmu, kāmēr bez TensorFlow klasifikācija nostrādāja pareizi. Ar parējiem burtiem arī ir redzamas problēmas - B tiek pieskaitīts pie 2. klases. Vispirms domāju, ka epohu skaits ir pie vainas, bet, darot 2. mājasdarbu, ieguvu nedaudz pieredzes un sapratu, ka pēc noklusējuma TensorFlow izmanto batch_size=32, bet oriģinālais modelis strādā batch_size=1 režīmā. Pārbaudīsim:

In [10]:
model.fit(np_letters, targets, batch_size=1, epochs=1000, verbose=0)
predictions = model.predict(np_letters)

print(predictions)

[[0.46556696 0.20971623 0.28771672 0.03700005]
 [0.3171911  0.41533726 0.21253535 0.05493634]
 [0.4245003  0.29753134 0.23495908 0.0430093 ]
 [0.39692888 0.41605994 0.15271471 0.03429645]
 [0.2911333  0.41151187 0.21722504 0.08012976]
 [0.29453287 0.4920148  0.16841164 0.04504079]
 [0.32661724 0.2329083  0.38682872 0.05364579]
 [0.31730422 0.19451658 0.44316012 0.04501912]
 [0.0874395  0.10797236 0.3486351  0.45595306]
 [0.0668207  0.09721947 0.22486073 0.6110991 ]
 [0.03653334 0.05261028 0.14601709 0.76483935]
 [0.02317738 0.04201355 0.11418518 0.82062393]]


Tagad sakrīt.